# Generated by Django 3.0.5 on 2020-05-01 12:46

from django.db import migrations, models
import django_extensions.db.fields
import shipments.helpers.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('seller_id', models.CharField(default=shipments.helpers.helper.get_24_char_uuid, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=15)),
                ('client_secret', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Seller detail',
            },
        ),
    ]
