# Generated by Django 3.0.5 on 2020-05-02 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import shipments.helpers.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=shipments.helpers.helper.get_24_char_uuid, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=50)),
                ('client_secret', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('access_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Seller detail',
            },
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.CharField(default=shipments.helpers.helper.get_24_char_uuid, max_length=24, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('pin_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer detail',
            },
        ),
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('id', models.CharField(default=shipments.helpers.helper.get_24_char_uuid, max_length=24, primary_key=True, serialize=False)),
                ('shipment_id', models.IntegerField(unique=True)),
                ('shipment_date', models.DateTimeField()),
                ('transport_id', models.CharField(max_length=30, unique=True)),
                ('transport_label', models.CharField(blank=True, max_length=15, null=True)),
                ('shipment_reference', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSED', 'PROCESSED')], default='PENDING', max_length=30)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipments.CustomerDetails')),
            ],
            options={
                'verbose_name': 'Shipment detail',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.CharField(default=shipments.helpers.helper.get_24_char_uuid, max_length=24, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=30, unique=True)),
                ('order_item_id', models.CharField(max_length=30)),
                ('order_date', models.DateTimeField()),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField()),
                ('order_condition', models.CharField(max_length=30)),
                ('fulfilment_method', models.CharField(max_length=3)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shipments.ShipmentDetails')),
            ],
            options={
                'verbose_name': 'Order detail',
            },
        ),
    ]
