# Generated by Django 3.0.5 on 2020-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20200501_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetails',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
